= Kraft Mode in strimzi world

Environment Setup:

Streams for Apache Kafka 2.8.0-0 provided by Red Hat

Prerequisites:

Install Streams for Apache Kafka 2.8.0: from OperatorHub

== New Deployment of Kraft

NOTE: KRaft can only be used with a Kafka cluster that uses `KafkaNodePool` resources.

To deploy a Kafka cluster in KRaft mode, you must use the KafkaNodePool resources.

[source, yaml,indent=0]
----
oc apply -f - <<EOF
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka
  labels:
    strimzi.io/cluster: dev-cluster
spec:
  replicas: 3
  roles:
    - broker
    - controller
  storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
EOF
----

To use KRaft, you still need to use the `annotations` on the Kafka custom resource (`strimzi.io/kraft: enabled`)

[source, yaml,indent=0]
----
oc apply -f - <<EOF
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: dev-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:   
  kafka:
    version: 3.8.0
    # The replicas field is required by the Kafka CRD schema while the KafkaNodePools feature gate is in alpha phase.
    # But it will be ignored when Kafka Node Pools are used
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.6"
    # The storage field is required by the Kafka CRD schema while the KafkaNodePools feature gate is in alpha phase.
    # But it will be ignored when Kafka Node Pools are used
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
  # The ZooKeeper section is required by the Kafka CRD schema while the UseKRaft feature gate is in alpha phase.
  # But it will be ignored when running in KRaft mode
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
EOF
----

NOTE: The `.spec.zookeeper` section in the Kafka custom resource is ignored in `KRaft mode` and should be removed from the custom resource.
The .spec.kafka.replicas property in the Kafka custom resource is ignored when node pools are used and should be removed from the custom resource.
The .spec.kafka.storage section in the Kafka custom resource is ignored when node pools are used and should be removed from the custom resource.
inter.broker.protocol.version is not used in KRaft-based Kafka clusters and should be removed from the Kafka custom resource.

[source, yaml,indent=0]
----
oc get k dev-cluster -o yaml | yq .status.conditions
----
[source, yaml,indent=0]
----
- lastTransitionTime: "2024-12-18T11:41:17.401143148Z"
  status: "True"
  type: Ready
----

== Migration from Zookeper to Kraft

Migrate your Strimzi-operated cluster from ZooKeeper to KRaft

  https://strimzi.io/blog/2024/03/22/strimzi-kraft-migration/
