= Kraft Mode in strimzi world

Environment Setup:

Streams for Apache Kafka 2.8.0-0 provided by Red Hat

Prerequisites:

Install Streams for Apache Kafka 2.8.0: from OperatorHub

== New Deployment of Kraft

IMPORTANT: KRaft can only be used with a Kafka cluster that uses `KafkaNodePool` resources.

To deploy a Kafka cluster in KRaft mode, you must use the KafkaNodePool resources.

[source, yaml,indent=0]
----
oc apply -f https://raw.githubusercontent.com/aboucham/strimzi-kafka-tutorial/refs/heads/main/kafka/KafkaNodePool-dev-cluster.yaml
----

To use KRaft, you still need to use the `annotations` on the Kafka custom resource (`strimzi.io/kraft: enabled`)

[source, yaml,indent=0]
----
oc apply -f https://raw.githubusercontent.com/aboucham/strimzi-kafka-tutorial/refs/heads/main/kafka/kafka-dev-cluster.yaml
----

NOTE: The `.spec.zookeeper` section in the Kafka custom resource is ignored in `KRaft mode` and should be removed from the custom resource.
The .spec.kafka.replicas property in the Kafka custom resource is ignored when node pools are used and should be removed from the custom resource.
The .spec.kafka.storage section in the Kafka custom resource is ignored when node pools are used and should be removed from the custom resource.
inter.broker.protocol.version is not used in KRaft-based Kafka clusters and should be removed from the Kafka custom resource.

[source, yaml,indent=0]
----
oc apply -f https://raw.githubusercontent.com/aboucham/strimzi-kafka-tutorial/refs/heads/main/kafka/kafka-kraft-dev-cluster.yaml
----

[source, yaml,indent=0]
----
oc get k dev-cluster -o yaml | yq .status.conditions
----
[source, yaml,indent=0]
----
- lastTransitionTime: "2024-12-18T11:41:17.401143148Z"
  status: "True"
  type: Ready
----

== Migration from Zookeper to Kraft

Migrate your Strimzi-operated cluster from ZooKeeper to KRaft

[source, yaml,indent=0]
----
oc apply -f https://raw.githubusercontent.com/aboucham/strimzi-kafka-tutorial/refs/heads/main/kafka/kafka-zk-my-cluster.yaml
----

=== Starting the migration:

[source, yaml,indent=0]
----
oc annotate k my-cluster strimzi.io/node-pools="enabled"
oc annotate k my-cluster strimzi.io/kraft="disabled"
----

1. Deploy a `KafkaNodePool` CR to provision the KRaft controllers. 

[source, yaml,indent=0]
----
oc apply -f - <<EOF
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
EOF
----

2. Change the `strimzi.io/kraft` annotation on the `Kafka` CR from `disabled` to `migration` to initiate the process:

[source, yaml,indent=0]
----
oc annotate k my-cluster strimzi.io/kraft="migration" --overwrite
----
