= Deploying Your Streams Console: A Step-by-Step Guide

Environment Setup:

- Streams for Apache Kafka 3.0.1-2 provided by Red Hat
- Streams for Apache Kafka Console 3.0.1-3 provided by Red Hat

----
oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/amq-streams.openshift-operators: ""
  name: amq-streams
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: amqstreams.v3.0.0-13
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/amq-streams-console.openshift-operators: ""
  name: amq-streams-console
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: amq-streams-console
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: amq-streams-console.v3.0.0-10
EOF
----

== Install Kafka Cluster 

First, we will deploy a Kafka cluster `kafka-cluster` Kraft Based:

[source, yaml,indent=0]
----
oc apply -f https://raw.githubusercontent.com/aboucham/strimzi-kafka-tutorial/refs/heads/main/kafka/full-Kafka-cluster-kraft.yaml
----

== Deploy Streams Console:

- `Plain` listener connection with Anonymous User since credentials is provided:

----
oc project strimzi

export KAFKA_CR_NAME="kafka-cluster"
export UI_CONSOLE_URL="my-console-ui.apps.abouchama-ai.emea.aws.cee.support"
export NAMESPACE="strimzi"
export KAFKA_LISTENER_NAME="plain"
# Name of the `KafkaUser` resource used to connect to Kafka
# This is optional if properties are used to configure the user
export KAFKA_CONSOLE_USER="console-kafka-user"
----

----
cat <<'EOF' | envsubst | oc apply -f -
apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: my-console
spec:
  hostname: $UI_CONSOLE_URL
  kafkaClusters:
    - name: $KAFKA_CR_NAME
      namespace: $NAMESPACE
      listener: $KAFKA_LISTENER_NAME
      credentials:
        kafkaUser:
          name: $KAFKA_CONSOLE_USER
EOF
----

- Prompt authentication page
- `Plain` listener connection with Anonymous User since credentials is provided:

----
cat <<'EOF' | envsubst | oc apply -f -
apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: my-console
spec:
  hostname: $UI_CONSOLE_URL
  kafkaClusters:
    - name: $KAFKA_CR_NAME
      namespace: $NAMESPACE
      listener: $KAFKA_LISTENER_NAME
EOF
----

- Prompt authentication page
- `tls` listener connection with Anonymous User since credentials is provided:

export KAFKA_LISTENER_NAME="tls"

----
cat <<'EOF' | envsubst | oc apply -f -
apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: my-console
spec:
  hostname: $UI_CONSOLE_URL
  kafkaClusters:
    - name: $KAFKA_CR_NAME
      namespace: $NAMESPACE
      listener: $KAFKA_LISTENER_NAME
EOF
----

== Streams Console OIDC
=== Deploy KeyCloak 26 

-----
oc new-project keycloak
oc project keycloak
-----

# Deploy KeyCloak Subscription:

----
oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/rhbk-operator.keycloak: ""
  name: rhbk-operator
  namespace: keycloak
spec:
  channel: stable-v26.2
  installPlanApproval: Automatic
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhbk-operator.v26.2.9-opr.1
EOF
----

# Deploy Keycloak 26 Instance:

----
oc apply -f https://raw.githubusercontent.com/aboucham/strimzi-kafka-tutorial/refs/heads/main/keycloak/keycloak-install.yaml
----





[source, yaml,indent=0]
----
----

With that, you will end up with the following list of pods:

[source, yaml,indent=0]
----
----

Log shows:

[source, yaml,indent=0]
----
amq-streams-cluster-operator-v2.8.0-0-6d966f74f5-f5prd strimzi-cluster-operator 2024-12-19 09:50:49 INFO  KafkaRoller:744 - Reconciliation #8319(timer) Kafka(kraft/my-cluster): Dynamic update of pod my-cluster-broker-0/0 was successful.
----
