apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: example
spec:
  hostname: example-console.apps.abouchama-ai.emea.aws.cee.support
  kafkaClusters:
    - credentials:
        kafkaUser:
          name: console-kafka-user
      listener: plain
      name: kafka-cluster
      namespace: strimzi
      security:
        roles:
          - name: developers
            rules:
              - privileges:
                  - GET
                  - LIST
                resources:
                  - topics
                  - topics/records
                  - consumerGroups
                  - rebalances
          - name: administrators
            rules:
              - privileges:
                  - GET
                  - LIST
                  - CREATE
                  - DELETE
                  - UPDATE
                resources:
                  - topics
                  - topics/records
                  - consumerGroups
                  - rebalances
                  - nodes/configs
                  - nodes
              - privileges:
                  - UPDATE
                resources:
                  - consumerGroups
                  - rebalances
  security:
    oidc:
      authServerUrl: 'https://keycloak-host.apps.abouchama-ai.emea.aws.cee.support/realms/console-streams'
      clientId: console-streams-ui
      clientSecret:
        valueFrom:
          secretKeyRef:
            key: client-secret
            name: my-oidc-secret
      trustStore:
        content:
          valueFrom:
            secretKeyRef:
              key: tls.crt
              name: oidc-ca-certificates
        type: PEM
    roles:
      - name: developers
        rules:
          - privileges:
              - ALL
            resourceNames:
              - kafka-cluster
            resources:
              - kafkas
      - name: administrators
        rules:
          - privileges:
              - ALL
            resourceNames:
              - kafka-cluster
              - '*'
            resources:
              - kafkas
    subjects:
      - claim: groups
        include:
          - kafka-devs
        roleNames:
          - developers
      - claim: groups
        include:
          - kafka-admins
        roleNames:
          - administrators
