apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: $CONSOLE_CR_NAME
  namespace: $NAMESPACE
spec:
  hostname: $UI_CONSOLE_URL
  kafkaClusters:
    - credentials:
        kafkaUser:
          name: $KAFKA_CONSOLE_USER
      listener: $KAFKA_LISTENER_NAME
      name: $KAFKA_CR_NAME
      namespace: $NAMESPACE
      security:
        roles:
          - name: $DEV_ROLE
            rules:
              - privileges:
                  - GET
                  - LIST
                resources:
                  - topics
                  - topics/records
                  - consumerGroups
                  - rebalances
          - name: $ADMIN_ROLE
            rules:
              - privileges:
                  - GET
                  - LIST
                  - CREATE
                  - DELETE
                  - UPDATE
                resources:
                  - topics
                  - topics/records
                  - consumerGroups
                  - rebalances
                  - nodes/configs
                  - nodes
              - privileges:
                  - UPDATE
                resources:
                  - consumerGroups
                  - rebalances
  security:
    oidc:
      authServerUrl: $OIDC_Discovery_URL
      clientId: $CLIENT_ID
      clientSecret:
        valueFrom:
          secretKeyRef:
            key: client-secret
            name: my-oidc-secret
# rm tls.crt
# oc extract secret/example-tls-secret -n keycloak --confirm
# oc create secret generic oidc-ca-certificates --from-file=tls.crt
#
#      trustStore:
#        content:
#          valueFrom:
#            secretKeyRef:
#              key: tls.crt
#              name: oidc-ca-certificates
#        type: PEM
    roles:
      - name: $DEV_ROLE
        rules:
          - privileges:
              - GET
              - LIST
            resourceNames:
              - $KAFKA_CR_NAME
            resources:
              - kafkas
      - name: $ADMIN_ROLE
        rules:
          - privileges:
              - ALL
            resourceNames:
              - '*'
            resources:
              - kafkas
    subjects:
      - claim: groups
        include:
          - $DEV_GROUP
        roleNames:
          - $DEV_ROLE
      - claim: groups
        include:
          - $ADMIN_GROUP
        roleNames:
          - $ADMIN_ROLE
